/* Genesys Field Cards v2 — content
   VERBATIM from genesys_field_cards_v2_content_pack.md. Do not paraphrase.
   Glossary inherited from genesys_content_pack.md section A. */

/* ---- Glossary terms (auto-linked in body text) ----
   key = canonical term shown; "type" controls tag colour;
   "def" = plain-English; "eq" = generic / Genesys equivalent bridge.
   "match" = array of strings to detect in rendered text (first occurrence per field). */
const GLOSSARY = [
  // Genesys terms
  { term:"AVA", type:"gx", match:["AVA"],
    def:"Agentic Virtual Agent — a third-generation virtual agent that goes beyond conversation to take action across systems and resolve customer requests end-to-end, within defined guardrails.",
    eq:"Generic: \u201CAI agent\u201D / autonomous virtual assistant (vs older intent-based chatbots and IVR menus)." },
  { term:"LAM", type:"gx", match:["Large Action Models (LAMs)","Large Action Models","LAMs","LAM"],
    def:"Large Action Model — purpose-built AI that executes actions under tight boundaries, minimising hallucination. Where an LLM talks, a LAM acts.",
    eq:"Generic: \u201Caction-oriented AI\u201D / agentic execution layer (contrast with LLM-only chatbots)." },
  { term:"MCP", type:"gx", match:["MCP"],
    def:"Model Context Protocol — middleware standard that lets AI safely pass context to and from external models and tools.",
    eq:"Generic: \u201CAI integration protocol\u201D / context bridge." },
  { term:"GPR", type:"gx", match:["Genesys Predictive Routing (GPR)","GPR"],
    def:"Genesys Predictive Routing — AI that routes each interaction to the best queue or agent based on skills, history, and predicted outcome.",
    eq:"Generic: \u201Cintelligent routing\u201D / AI-driven skills-based routing." },
  { term:"GPE", type:"gx", match:["GPE"],
    def:"Genesys Predictive Engagement — AI that spots intent on web and app journeys and triggers proactive engagement before the customer reaches the contact centre.",
    eq:"Generic: \u201Cproactive engagement\u201D / digital intent detection." },
  { term:"STA", type:"gx", match:["STA"],
    def:"Speech & Text Analytics (within WEM) — AI that analyses conversations across voice and digital channels for topics, sentiment, compliance, and coaching opportunities.",
    eq:"Generic: \u201Cconversation analytics\u201D / interaction analytics." },
  { term:"WEM", type:"gx", match:["WEM"],
    def:"Workforce Engagement Management — the suite covering workforce optimisation: scheduling, forecasting, quality management, coaching and gamification, wrapped around STA insights.",
    eq:"Generic: \u201Cworkforce optimisation\u201D / WFO suite." },

  // Metrics
  { term:"AHT", type:"metric", match:["AHT"],
    def:"Average Handle Time — the time an agent spends on an interaction, including talk time and after-call work.",
    eq:"What moves it (Genesys): GPR, Agent Copilot, AVA full-context handoff." },
  { term:"FCR", type:"metric", match:["first-call resolution (FCR)","FCR"],
    def:"First Contact Resolution — the percentage of issues resolved without callback or escalation. (First-call resolution is the voice-only variant.)",
    eq:"What moves it (Genesys): AVA, GPR, knowledge surfacing." },
  { term:"CES", type:"metric", match:["CES"],
    def:"Customer Effort Score — how hard the customer had to work to resolve their issue.",
    eq:"What moves it (Genesys): AVA end-to-end resolution, GPE, unified data model." },
  { term:"NPS", type:"metric", match:["NPS"],
    def:"Net Promoter Score — customer likelihood to recommend; the compound effect of resolution, effort reduction, and experience consistency.",
    eq:"Moves with resolution quality and effort reduction over time." },
  { term:"containment", type:"metric", match:["containment rate","containment"],
    def:"Containment (rate) — the percentage of interactions resolved by self-service or AI end-to-end, without agent involvement. Distinct from deflection.",
    eq:"Primary lever: AVA. Not the same as deflection." },
  { term:"first-touch resolution", type:"metric", match:["first-touch resolution (FTR)","First-touch resolution (FTR)","first-touch resolution","First-touch resolution","FTR"],
    def:"First-touch resolution (FTR) — the percentage of customer issues resolved in the first interaction, regardless of channel. Distinct from first-call resolution, which is voice-only.",
    eq:"The metric of the experience economy; the operational signature of the loyalty/efficiency thesis." },

  // Generic Conversational CX terms
  { term:"intent recognition", type:"generic", match:["Intent recognition","intent recognition"],
    def:"The part of a conversational AI system that works out what the customer is actually trying to do, in their own words \u2014 not menu paths or keywords.",
    eq:"Genesys equivalent: built into AVA." },
  { term:"routing", type:"generic", match:["Routing","routing"],
    def:"The system that decides where an interaction goes next \u2014 which queue, skill, agent, bot, or channel.",
    eq:"Genesys equivalent: GPR (Genesys Predictive Routing)." },
  { term:"deflection", type:"generic", match:["deflection","Deflection","deflecting","deflected"],
    def:"Diverting an interaction away from a human agent \u2014 typically into self-service or a chatbot \u2014 regardless of whether the issue is actually resolved there.",
    eq:"Genesys equivalent / contrast: AVA containment (resolution, not just diversion)." },
  { term:"agent assist", type:"generic", match:["Agent assist","agent assist"],
    def:"Real-time AI help for human agents during live interactions \u2014 live transcription, summarisation, next-best-action prompts, knowledge surfacing, sentiment and compliance flags.",
    eq:"Genesys equivalent: Agent Copilot (the newer, more intelligent generation of the category; \u201Cagent assist\u201D is the older terminology still used by most competitors)." },
  { term:"Agent Copilot", type:"gx", match:["Agent Copilot"],
    def:"Genesys\u2019s real-time AI assistant for human agents \u2014 surfaces context, drafts summaries, suggests next-best-actions, and updates CRM records inline. Sits on the unified data model shared with routing, knowledge, and analytics.",
    eq:"Generic: \u201Cagent assist\u201D (older terminology). Agent Copilot is the newer, more capable generation." },
  { term:"knowledge management", type:"generic", match:["Knowledge management","knowledge management"],
    def:"The structured content base \u2014 articles, policies, scripts, procedures \u2014 that AI agents, chatbots, and human agents all draw from.",
    eq:"Genesys equivalent: Resource Center (editorial source of truth) + Knowledge Workbench (in-product authoring and surfacing)." },
  { term:"Resource Center", type:"gx", match:["Resource Center"],
    def:"Genesys\u2019s central documentation hub \u2014 the editorial source of truth used internally (Genesys\u2019s own custom GPTs draw from it) and consumed by partners and customers.",
    eq:"Generic: editorial knowledge base / canonical product documentation." },
  { term:"Knowledge Workbench", type:"gx", match:["Knowledge Workbench"],
    def:"The in-product capability inside Genesys Cloud that authors, versions, and surfaces knowledge articles to virtual agents and Agent Copilot.",
    eq:"Generic: knowledge authoring + surfacing layer for conversational AI." },
  { term:"guardrails", type:"generic", match:["Guardrails","guardrails"],
    def:"The rules that constrain what an AI is allowed to do, say, or decide \u2014 permitted scope, actions, tone, and required behaviours, defined as policy and enforced at runtime.",
    eq:"Genesys equivalent: AI Studio." },
  { term:"hallucination mitigation", type:"generic", match:["Hallucination mitigation","hallucination mitigation","Hallucination","hallucination"],
    def:"Stopping an AI from confidently producing plausible-sounding but wrong answers \u2014 via retrieval-augmented generation, structured prompting, output filtering, confidence scoring, and architectural choices like Large Action Models.",
    eq:"Genesys equivalent: LAM design + AI Studio guardrails." },
  { term:"orchestration", type:"generic", match:["Orchestration","orchestration","orchestrated","orchestrate"],
    def:"Coordinating every part of the customer journey \u2014 people, data, systems, channels, AI \u2014 into a single coherent experience that adapts in real time. AI is the conductor.",
    eq:"Genesys equivalent: Genesys experience orchestration (\u201CAI-Powered Experience Orchestration\u201D)." },
  { term:"autonomy spectrum", type:"generic", match:["autonomy spectrum","The autonomy spectrum"],
    def:"A four-level framework for how much independent action an AI may take: Suggest \u2192 Assist \u2192 Execute \u2192 Orchestrate. A design vocabulary, not a maturity ladder.",
    eq:"Used as a compliance vocabulary against EU AI Act risk tiers." }
];

/* ---- Concept cards (10), verbatim ---- */
const CONCEPTS = [
  { slug:"intent-recognition", n:1, title:"Intent recognition",
    teaser:"What the customer is actually asking for, in their words.",
    concept:"Intent recognition is the part of a conversational AI system that works out what the customer is actually trying to do, in their own words. Not \u201Cpress 2 for billing\u201D, but \u201CI think I\u2019ve been charged twice for the same thing\u201D. Older systems matched keywords or menu paths; modern systems use language models to infer intent from messy, ambiguous, real-world phrasing across voice, chat, email, and messaging. Getting intent wrong cascades into every downstream step \u2014 routing, knowledge retrieval, automation. Getting it right is the foundation everything else stands on.",
    emea:"EMEA buyers test intent recognition in languages and dialects most US-built systems were never trained on. A virtual agent that handles English fluently but stumbles in German, French, Italian, Portuguese, Arabic, or Dutch is a non-starter for a pan-European deployment. Beyond language coverage, EMEA buyers ask harder questions about training data provenance \u2014 what was the model trained on, where does that data sit, is it auditable under the EU AI Act. Intent recognition in EMEA isn\u2019t only a quality question; it\u2019s a sovereignty and compliance question with regulatory teeth.",
    genesys:"Genesys builds intent recognition into the wider experience orchestration layer, so an inferred intent doesn\u2019t just resolve a conversation \u2014 it informs routing, knowledge surfacing, Agent Copilot, and analytics across the journey. The point isn\u2019t that Genesys has the best NLU model in isolation; it\u2019s that an intent recognised in the front door is the same intent passed to the human agent if escalation happens, the same intent that shapes the post-call summary, and the same intent feeding journey analytics. Intent becomes a unit of orchestration, not just a chatbot input.",
    pureplay:"Pureplay conversational AI vendors often have excellent intent recognition \u2014 that\u2019s the core of their product, and they iterate fast on the model itself. Where they\u2019re weaker is what happens with that intent once recognised. If the intent stays inside the conversation layer and doesn\u2019t flow to the agent desktop, the routing engine, or the system of record, the customer ends up repeating themselves on escalation. The model is sharp; the orchestration is the buyer\u2019s problem. For an EMEA buyer comparing options, the question is whether intent is a feature or a foundation." },

  { slug:"routing", n:2, title:"Routing",
    teaser:"Predictive, skills-based, AI-driven \u2014 the right interaction to the right resource.",
    concept:"Routing is the system that decides where an interaction goes next \u2014 which queue, which skill, which agent, which bot, which channel. The simplest version is round-robin or skill-based: match a call to anyone qualified to handle it. Modern routing is predictive: it weighs agent skill, current load, customer history, predicted handle time, predicted CSAT outcome, and language. Done well, routing is invisible to the customer and feels obvious in hindsight. Done badly, it\u2019s the most common cause of avoidable escalations, repeated explanations, and the \u201Clet me transfer you\u201D experience customers hate.",
    emea:"EMEA contact centres frequently route across multiple countries, languages, and regulatory regimes in a single workflow. A call originating in Spain may need to land with a Spanish-speaking agent who\u2019s also certified to handle a specific banking product under local rules. Routing decisions can carry data sovereignty implications: which country\u2019s agents are allowed to see which customer data. Routing isn\u2019t just an efficiency lever in EMEA \u2014 it\u2019s a compliance surface. AI-driven routing that treats this as a constraint, not an afterthought, is the difference between scaling cleanly and explaining yourself to a regulator.",
    genesys:"Genesys Predictive Routing (GPR) is the named capability. It uses machine learning trained on the customer\u2019s own historical interaction data to match each interaction to the best available resource by predicted outcome \u2014 not just availability. Because routing sits inside the same platform as the agent desktop, knowledge, and analytics, the prediction feeds and is fed by the rest of the journey. The commercial story isn\u2019t \u201Csmarter routing\u201D; it\u2019s \u201Cbest resource for every interaction, every time, with the learning loop closed\u201D. That\u2019s where the loyalty-and-efficiency story lands at the operational level.",
    pureplay:"Most pureplay conversational AI vendors don\u2019t do routing at all \u2014 their product ends at the conversation, and routing is left to whatever the customer is already running (often a legacy ACD). That\u2019s a defensible architecture, but it pushes integration burden to the buyer. Some newer agentic AI vendors are starting to make routing claims, but typically without the long-tail training data Genesys has accumulated across millions of agent interactions. For an EMEA buyer, the question is whether the routing engine has seen enough EMEA-specific patterns to predict outcomes credibly." },

  { slug:"containment-vs-deflection", n:3, title:"Containment vs deflection",
    teaser:"The most-confused pair in the discipline \u2014 one resolves, the other diverts.",
    concept:"These two get used interchangeably and shouldn\u2019t be. <strong>Deflection</strong> means diverting an interaction away from a human agent \u2014 typically by sending the customer to self-service or a chatbot, regardless of whether they resolve their issue there. <strong>Containment</strong> means resolving the interaction within self-service or AI, end-to-end, without the customer needing to escalate. A deflected call that ends in a callback is still a cost \u2014 sometimes a bigger cost than handling it the first time. A contained interaction is a real saving. The whole point of agentic AI is shifting the metric from deflection to containment.",
    emea:"EMEA regulators and consumer protection bodies are increasingly intolerant of deflection that masquerades as resolution. Pushing customers into self-service that doesn\u2019t work, then making them call back, is starting to attract regulatory and reputational scrutiny \u2014 particularly in financial services under the UK FCA Consumer Duty and equivalent EU frameworks. EMEA buyers who confuse deflection with containment in their pilot metrics build deployments that look efficient on a dashboard but generate complaint volume, regulatory exposure, and brand damage downstream. The vocabulary discipline matters commercially.",
    genesys:"Genesys\u2019s positioning on agentic virtual agents is explicitly about containment, not deflection \u2014 resolving requests end-to-end, taking actions across systems, and handing off complete context only when escalation is genuinely needed. The commercial narrative is that high containment correlates with high CSAT, because the customer\u2019s problem actually got solved. This is the operational expression of the loyalty/efficiency paradox ending: the same lever that reduces cost-per-contact also lifts NPS and FCR, because the AI isn\u2019t just deflecting; it\u2019s resolving.",
    pureplay:"Pureplay AI vendors will claim high containment, and sometimes they have it \u2014 for the specific journeys they\u2019ve trained on. The gap typically shows in the long tail: the ambiguous case, the cross-system request, the interaction that needs to touch billing, fraud, and knowledge at once. Pureplay models contain the conversation; they don\u2019t always contain the resolution. The honest EMEA buyer asks for containment numbers measured at <em>issue level</em> over 90 days, not at <em>session level</em> over a demo week." },

  { slug:"agent-assist", n:4, title:"Agent assist",
    teaser:"Real-time AI help for human agents during interactions.",
    concept:"Agent assist is real-time AI help for human agents during live interactions. The most common features: live transcription, automatic call summarisation, next-best-action prompts, knowledge surfacing tied to detected intent, sentiment alerts, and compliance flags. The point of agent assist is not to replace the agent \u2014 it\u2019s to compress the cognitive load so the agent spends their attention on judgement and empathy, not on searching screens or typing notes. It\u2019s the most under-rated piece of the conversational CX stack, because the productivity gain is large and the customer often doesn\u2019t notice anything has changed.",
    emea:"Agent assist is where EMEA\u2019s data-flow reality becomes operational. To surface the right knowledge article or the right next-best-action, the AI has to draw on customer history, system of record, and policy \u2014 across countries with different residency rules. An agent assist deployment that works in one country may not be deployable in the next without rework. EMEA buyers also weigh works council and union sensitivities: agent assist done badly feels like surveillance; done well, it\u2019s a coaching and productivity multiplier. The change-management story is at least as important as the technical one.",
    genesys:"Genesys calls this category <strong>Agent Copilot</strong> \u2014 a deliberate choice, because \u201Cagent assist\u201D is the older, less intelligent generation of the category (still the term most competitors use). Agent Copilot sits on the unified data model that underpins routing, knowledge, and analytics: it surfaces context, drafts summaries, suggests next-best-actions, and updates CRM records inline. The commercial story is that Agent Copilot closes the loyalty/efficiency loop in real time \u2014 the customer feels heard because the agent isn\u2019t typing, and the agent finishes faster because the AI did the back-office work in parallel. Loyalty and efficiency from a single feature, on a single data flow.",
    pureplay:"Pureplay agent assist vendors exist \u2014 most still use the older \u201Cagent assist\u201D label \u2014 and they often plug into an existing contact centre as an overlay. The trade-off is that the overlay sees only what it\u2019s integrated with, and integration becomes the buyer\u2019s project. Each pureplay tool tends to own its own data pipe to the agent\u2019s screen, leading to \u201CAI tab sprawl\u201D \u2014 three or four AI panels competing for the agent\u2019s attention. Pureplay agent assist optimises one moment; orchestrated Agent Copilot optimises the journey." },

  { slug:"knowledge-management", n:5, title:"Knowledge management",
    teaser:"The structured content base AI and agents draw from.",
    concept:"Knowledge management in conversational CX is the structured content base \u2014 articles, policies, scripts, procedures \u2014 that AI agents, chatbots, and human agents all draw from. Bad knowledge management is the silent killer of AI deployments: even the best model produces wrong, stale, or contradictory answers if the underlying knowledge is fragmented across SharePoint, intranet pages, scripts, and tribal memory. Modern knowledge management is about consolidation, versioning, ownership, and embedding the knowledge into the same orchestration layer the AI and agents use \u2014 so every channel pulls from the same source of truth.",
    emea:"EMEA knowledge management is multi-lingual, multi-jurisdictional, and version-sensitive. A policy that\u2019s correct in Germany may be wrong in France; a piece of regulatory guidance that\u2019s current in October may be out of date in November. EMEA buyers care about who <em>owns</em> a knowledge article, when it was last reviewed, and whether the AI can be prevented from citing a deprecated version. Under EU AI Act expectations, a virtual agent confidently quoting outdated policy is not just an experience problem \u2014 it can be a compliance breach. Knowledge governance is AI governance in disguise.",
    genesys:"Genesys runs two complementary surfaces. <strong>Resource Center</strong> is the editorial source of truth \u2014 the central documentation hub Genesys uses internally (their own custom GPTs draw from it) and the same backbone partners and customers consume. <strong>Knowledge Workbench</strong> is the in-product capability that authors, versions, and surfaces knowledge to virtual agents and Agent Copilot inside Genesys Cloud. The commercial story is that knowledge becomes one editorial truth across every channel, with guardrails enforcing that AI only answers from approved content. This is where hallucination mitigation and knowledge management blur: the cleanest way to prevent a virtual agent making things up is to make sure it only ever answers from a governed source.",
    pureplay:"Pureplay vendors increasingly offer their own knowledge layer, sometimes ingesting your existing documents into a vector store. The architecture is elegant but creates a fork: the AI\u2019s knowledge and the human agent\u2019s knowledge are now two different things, maintained separately, drifting over time. The buyer ends up either maintaining two knowledge bases or accepting that their AI and their agents are answering customers from different versions of the truth. For regulated industries, that\u2019s a hard sell to the audit committee." },

  { slug:"guardrails", n:6, title:"Guardrails",
    teaser:"What AI is allowed to do, defined as policy.",
    concept:"Guardrails are the rules that constrain what an AI is allowed to do, say, or decide. They define the model\u2019s permitted scope (what topics it can address), permitted actions (what systems it can touch), permitted tone (how it should and shouldn\u2019t sound), and required behaviours (e.g. always offer escalation, never make claims about pricing). Guardrails are how you turn a general-purpose AI into a fit-for-purpose enterprise AI. They\u2019re defined as policy, configured in software, and enforced at runtime \u2014 not coded line-by-line per use case.",
    emea:"The EU AI Act, in force since 2024, classifies AI systems by risk and imposes obligations accordingly. Conversational CX often falls in the limited-to-high-risk band, with high-risk classifications triggered by decisions affecting credit, eligibility, employment, or service denial. Guardrails are how a buyer evidences that high-risk AI is operating within its declared scope \u2014 what it can do, what it can\u2019t, and what gets logged. EMEA buyers don\u2019t want guardrails as a marketing line; they want them as a policy surface they can hand to their compliance officer and their regulator.",
    genesys:"Genesys AI Studio is the surface where guardrails are defined, observed, and audited. Goals, permissions, and constraints are set per agent; every action is logged with a reason; behaviour can be reversed or adjusted without re-platforming. The commercial story is that guardrails aren\u2019t a compliance afterthought bolted on after deployment \u2014 they\u2019re the foundation the agent is built on. This matters in EMEA because it changes the conversation with Risk & Compliance from \u201Ccan we get sign-off\u201D to \u201Chere\u2019s our governance posture, evidenced\u201D.",
    pureplay:"Pureplay vendors offer guardrails too, but typically scoped to the conversation: what the bot can and can\u2019t say. They\u2019re often weaker on action guardrails \u2014 what the AI can do across systems, with what permissions, under what audit trail \u2014 because their product doesn\u2019t span those systems. For a low-risk conversational use case that\u2019s fine. For a high-risk EMEA banking, insurance, or public sector deployment under EU AI Act scrutiny, the guardrail surface needs to cover actions as well as words." },

  { slug:"hallucination-mitigation", n:7, title:"Hallucination mitigation",
    teaser:"Why LAMs vs LLMs matters in regulated CX.",
    concept:"Hallucination is when an AI confidently produces an answer that\u2019s plausible-sounding but wrong. Large language models are particularly prone to it because they\u2019re trained to generate fluent text, not to verify facts. Mitigation strategies include retrieval-augmented generation (forcing the model to answer only from approved sources), structured prompting, output filtering, confidence scoring, and \u2014 increasingly \u2014 architectural choices like Large Action Models, which constrain the AI to executing defined actions rather than generating open-ended responses. No mitigation eliminates hallucination; the goal is to make it rare, detectable, and reversible.",
    emea:"Hallucination in regulated EMEA contexts isn\u2019t a quality bug \u2014 it\u2019s a regulatory event. An AI that misquotes policy to a customer in financial services, healthcare, or public sector triggers obligations under the EU AI Act, consumer protection law, and sector-specific rules. UK FCA Consumer Duty in particular makes the brand liable for the accuracy of automated communications. EMEA buyers ask harder questions about mitigation than US peers, and they expect concrete answers \u2014 architectural choices, monitoring, lineage, and incident response \u2014 not assurances. \u201COur model rarely hallucinates\u201D is not an acceptable answer in a procurement document.",
    genesys:"Genesys\u2019s approach combines architectural and operational mitigation. Large Action Models (LAMs) are used where actions are needed, constraining the AI to a permitted action space rather than open generation. Knowledge-grounded responses use approved content only. AI Studio observes outputs and flags anomalies. The commercial story is that mitigation is layered \u2014 architectural, content-grounded, observed, and reversible \u2014 and built into the platform, not delegated to the customer\u2019s MLOps team. For a Risk & Compliance buyer, this is the difference between \u201Cwe trust the vendor\u201D and \u201Cwe can evidence the controls\u201D.",
    pureplay:"Pureplay vendors are usually transparent about their mitigation strategy \u2014 confidence thresholds, RAG pipelines, human-in-the-loop checks \u2014 and many invest heavily in it. The honest gap is that mitigation in a pureplay conversation layer can only cover what the layer sees: the conversation itself. If hallucination shows up in a downstream action (a wrong account credited, a wrong policy quoted in a follow-up email), it\u2019s outside the pureplay\u2019s observable surface. Orchestrated AI mitigates across the journey; pureplay AI mitigates the chat." },

  { slug:"orchestration", n:8, title:"Orchestration", thesis:true,
    teaser:"The single most important concept in this app \u2014 the paradox-ender.",
    concept:"Orchestration is the coordination of every part of the customer journey \u2014 people, data, systems, channels, AI \u2014 into a single coherent experience that adapts in real time. Where automation handles one task and routing decides one handoff, orchestration decides how the whole interaction should flow, end-to-end, based on context that updates as the conversation moves. Orchestration is the architectural answer to fragmented CX: instead of stitching point solutions together, the journey itself is the system, and AI is the conductor. It\u2019s the most important concept in modern conversational CX, and the hardest to demonstrate in a demo.",
    emea:"EMEA\u2019s regulatory, linguistic, and operational complexity rewards orchestration disproportionately. A customer journey crossing UK, Germany, and France may touch three regulatory regimes, two languages, and four back-office teams (KYC, fraud, billing, support). Without orchestration, every handoff is a context-loss event and a compliance risk; with orchestration, the journey adapts as it moves. EMEA buyers who\u2019ve tried to build orchestration by integrating five vendors know the cost. The market has moved decisively toward platforms where orchestration is native, not assembled.",
    genesys:"\u201CAI-Powered Experience Orchestration\u201D is Genesys\u2019s stated category position, and it\u2019s not a marketing slogan \u2014 it\u2019s the architectural argument. Every Genesys capability (AVA, GPR, GPE, Agent Copilot, knowledge, WEM, STA) feeds and is fed by the orchestration layer. The commercial story is the loyalty/efficiency paradox ending: orchestration is the mechanism by which efficiency gains (containment, lower AHT, lower cost-per-contact) compound into loyalty gains (NPS, FCR, retention) instead of trading against them. This is the spine of the v2 thesis. If a buyer takes nothing else from a Genesys conversation, this is the concept that has to land.",
    pureplay:"Pureplay AI vendors orchestrate the conversation. Almost none orchestrate the journey \u2014 that\u2019s a different product category, with a different architectural footprint, and a different cost base. Some pureplays are honest about this and partner; others claim orchestration and deliver advanced conversation routing. The buyer\u2019s test is simple: ask the vendor to show what happens when a customer is escalated mid-conversation to a human agent in a different country with a different system of record. Conversation-layer orchestration ends at that handoff; experience orchestration carries through it." },

  { slug:"autonomy-spectrum", n:9, title:"The autonomy spectrum",
    teaser:"Suggest \u2192 assist \u2192 execute \u2192 orchestrate.",
    concept:"The autonomy spectrum is a four-level framework for describing how much independent action an AI is permitted to take: <strong>Suggest</strong> (AI offers an option, human decides), <strong>Assist</strong> (AI does part of the task alongside a human), <strong>Execute</strong> (AI completes a defined task end-to-end within guardrails), <strong>Orchestrate</strong> (AI coordinates multiple tasks, agents, and systems across the journey). It\u2019s not a maturity model \u2014 different use cases warrant different levels permanently. A password reset can be safely orchestrated; a mortgage decision should stay at suggest. The spectrum is a design vocabulary, not a destination.",
    emea:"The EU AI Act risk classifications map roughly onto the autonomy spectrum: higher autonomy on consequential decisions triggers higher-risk classification, with corresponding obligations. EMEA buyers use the autonomy spectrum not just as a design tool but as a compliance vocabulary \u2014 \u201Cthis use case is at Execute, with these guardrails, logged this way\u201D is exactly the structure an EU AI Act conformity assessment expects. The spectrum also clarifies internal conversations: a CFO and a Risk Officer can disagree about ambition without disagreeing about words, because the levels are unambiguous.",
    genesys:"Genesys frames its agentic capabilities explicitly against the spectrum, with AVA designed to operate across all four levels and AI Studio defining which level applies per use case. The commercial story is \u201Crisk-managed autonomy\u201D: you don\u2019t have to choose between conservative pilots and ambitious automation \u2014 you can run different journeys at different levels under one governance posture. This is what makes the loyalty/efficiency paradox solvable per use case, not just in aggregate: a brand can be highly automated on transactional journeys and highly human on relational ones, intentionally.",
    pureplay:"Pureplay agentic AI vendors typically build at Execute and Orchestrate by default \u2014 that\u2019s the product\u2019s reason for being. The gap is that the spectrum gets compressed: every use case is treated as equivalently agentic, with limited per-use-case governance. For an EMEA buyer running consumer-grade chatbots alongside high-risk decision flows, the lack of differentiation becomes the problem. A platform that supports all four levels under one governance surface is structurally easier to deploy than a pureplay that does Execute well and forces everything into that mode." },

  { slug:"first-touch-resolution", n:10, title:"First-touch resolution",
    teaser:"The metric of the experience economy \u2014 the one that operationalises the thesis.",
    concept:"First-touch resolution (FTR) is the percentage of customer issues resolved in the first interaction, regardless of channel \u2014 web, app, voice, chat, messaging. Distinct from first-call resolution (FCR), which is voice-only, FTR measures the experience economy: did the customer get what they came for, the first time they tried, wherever they started? It\u2019s the metric that aligns customer goals with operational ones. A high FTR means low effort for the customer and low cost-per-contact for the brand. It\u2019s also the metric most resistant to gaming, because the customer\u2019s behaviour confirms it.",
    emea:"EMEA brands operating across multiple countries struggle with FTR more than US peers because journeys cross channel, language, and back-office boundaries more often. A first touch on a German web app that ends in an English-language phone callback isn\u2019t first-touch resolution \u2014 it\u2019s a handoff dressed up. EMEA regulators are starting to look at metrics like FTR as proxies for customer treatment under consumer protection rules, particularly in financial services. A brand that can evidence high FTR across a multi-country footprint is evidencing both operational discipline and customer-centricity simultaneously.",
    genesys:"Paulette Toynton (Genesys VP Strategic Sales EMEA) named first-touch resolution explicitly as the goal of orchestrated CX: \u201COur goal should always be first-touch resolution\u2026 empower the customer to start and finish where they wanted to start and finish, not force them into a journey that takes them into another channel.\u201D This is where the v2 thesis becomes a metric: orchestration is what makes high FTR achievable, and high FTR is the operational signature of the loyalty/efficiency paradox ending. If you measure one thing across the journey, measure this.",
    pureplay:"Pureplay AI vendors will quote containment, deflection, and CSAT \u2014 rarely FTR, because FTR requires visibility across the journey their product doesn\u2019t span. They can measure first-touch resolution <em>within</em> the conversation, but not whether that customer needed to come back through a different channel two hours later. For the EMEA buyer evaluating the long-term operational impact of an AI investment, FTR measured across the journey is the most honest test. Pureplays will resist the question; orchestration vendors should welcome it." }
];

/* ---- Tension cards (5), verbatim ----
   "play" field uses [[slug|visible text]] markers -> rendered as clickable links. */
const TENSIONS = [
  { slug:"loyalty-vs-efficiency", n:1, title:"Loyalty vs efficiency", thesis:true,
    teaser:"The master tension \u2014 the app\u2019s thesis card. Frames the others.",
    tension:"Brands want their customers to feel valued and to come back \u2014 that\u2019s loyalty. They also need the operational efficiency to keep the lights on, fund growth, and pay for the experiences that build loyalty in the first place. For decades these felt like opposing levers: invest in people and service quality to drive loyalty, or invest in automation and process discipline to drive efficiency. The CX industry built playbooks for each, and most brands ended up doing both badly because they couldn\u2019t reconcile the two. This is the foundational tension every other tension in this app derives from.",
    persists:"The paradox persists because the tools haven\u2019t matched the ambition. Traditional automation deflects volume but degrades experience; traditional personalisation lifts experience but doesn\u2019t scale. Brands ended up with deflection-heavy IVRs alongside white-glove service for high-value customers, with everyone in the middle getting neither. Inside the contact centre, AHT and CSAT have been treated as opposing KPIs for so long that operations teams literally trade one against the other in weekly reviews. The paradox is structural in the metrics, the tools, and the org chart \u2014 not just in the philosophy.",
    play:"[[orchestration|Orchestration]] is the architectural answer \u2014 coordinating people, data, systems and AI so efficiency and loyalty stop trading against each other. [[first-touch-resolution|First-touch resolution]] is the operational signature: when FTR is high, AHT and CSAT both move in the right direction. [[containment-vs-deflection|Containment vs deflection]] is the discipline that prevents fake efficiency. [[agent-assist|Agent Copilot]] is where loyalty and efficiency become the same lever in real time. Together these concepts describe a system, not a feature \u2014 which is why the paradox needs an architectural answer, not a tactical one.",
    reconcile:"EMEA brands ending the paradox typically share three patterns. They consolidate onto one platform that spans automation, agent tooling, and analytics \u2014 so efficiency and experience are measured against the same data. They move the metric from cost-per-contact to first-touch resolution, so the team optimises customer outcomes and operational outcomes simultaneously. And they extend orchestration into the back office (KYC, fraud, compliance, marketing) so the data flows that drive loyalty don\u2019t stop at the contact centre door. The pattern is consolidation, metric realignment, and journey-wide data flow." },

  { slug:"containment-vs-experience-quality", n:2, title:"Containment vs experience quality",
    teaser:"Deflecting calls isn\u2019t the same as resolving them.",
    tension:"Containing interactions in self-service is the largest single lever for reducing cost-to-serve, and most CX leaders are under pressure to push containment up. But containment optimised in isolation degrades experience \u2014 customers get stuck in self-service that doesn\u2019t resolve their issue, then escalate angrier than they would have arrived. The tension is between the dashboard metric (containment up) and the customer\u2019s actual experience (effort up). It plays out daily in CX operations: every percentage point of containment gain risks being eaten by escalations, complaints, and CSAT drops if the AI can\u2019t actually resolve what it tried to handle.",
    persists:"Containment is easy to measure (did the call avoid an agent), experience is harder to measure (did the customer\u2019s problem actually get solved). The metric asymmetry biases the whole organisation toward optimising the wrong number. Compounding this, most legacy IVRs and early chatbots were designed for deflection \u2014 diverting volume \u2014 not containment, so the vocabulary and tooling drift apart. Vendors often quote containment in pitches without distinguishing it from deflection, which entrenches the confusion. Customers and regulators are catching up faster than the internal metrics are.",
    play:"[[containment-vs-deflection|Containment vs deflection]] is the vocabulary discipline that has to be in place before this tension can be reconciled. [[intent-recognition|Intent recognition]] determines whether the AI even understands what to contain. [[knowledge-management|Knowledge management]] determines whether the AI can credibly resolve what it\u2019s trying to contain. [[first-touch-resolution|First-touch resolution]] is the honest metric that ties containment to customer outcome. [[orchestration|Orchestration]] ensures that when containment fails, the handoff to a human preserves context so the customer isn\u2019t punished by the escalation.",
    reconcile:"The reconciliation pattern in EMEA is to move the executive metric off raw containment and onto first-touch resolution, measured at issue level across 30+ days. Pilots are scoped narrowly to journeys where the AI can credibly resolve \u2014 not all journeys, not all the time. Escalation is treated as a designed step, not a failure, with full context handoff. Knowledge and guardrails are governed centrally so the AI doesn\u2019t try to contain interactions it shouldn\u2019t. The brands that do this well stop talking about containment in board reports and start talking about customer-effort metrics instead." },

  { slug:"automation-pace-vs-auditability", n:3, title:"Automation pace vs auditability",
    teaser:"Speed of AI adoption vs EU AI Act and DORA reality.",
    tension:"The business wants to deploy AI quickly to capture efficiency gains; Risk, Compliance, and Legal need every AI decision to be explainable, logged, and reversible. The tension shows up most painfully in EMEA, where EU AI Act obligations and sector-specific rules (DORA, FCA Consumer Duty, GDPR) impose audit standards that don\u2019t bend for speed. Move too fast and you ship AI that fails a regulator\u2019s question; move too slow and you watch competitors land use cases you\u2019ve been debating for six months. Most brands fall on the slow side and lose ground, then over-correct.",
    persists:"The roles of \u201Cbuild it\u201D and \u201Cgovern it\u201D sit in different parts of the org, with different success metrics, different vocabularies, and different timelines. Engineering measures shipping velocity; Risk measures avoidance of incidents. The AI itself adds a new wrinkle: model behaviour can drift after deployment in ways traditional software doesn\u2019t, so even a clean audit at launch isn\u2019t permanent. Without shared governance tooling, every new AI use case becomes a fresh negotiation between teams, slowing the pace and creating exactly the audit gaps Risk feared.",
    play:"[[guardrails|Guardrails]] are the policy surface that makes governance a configuration, not a negotiation. [[hallucination-mitigation|Hallucination mitigation]] is the architectural choice that makes the AI auditable by design. [[autonomy-spectrum|The autonomy spectrum]] gives both sides a shared vocabulary for \u201Chow much independence does this use case need?\u201D \u2014 turning a values argument into a design decision. [[orchestration|Orchestration]] matters because a unified audit trail across the journey is dramatically easier to evidence than a stitched one across five vendors.",
    reconcile:"The brands moving fastest are the ones that invested in governance tooling early \u2014 a single surface where guardrails, autonomy levels, and audit logs are configured per use case. They classify every AI use case against EU AI Act risk tiers as part of design, not as a launch gate. They pre-agree the autonomy spectrum level with Risk for each journey type, so individual use cases don\u2019t re-litigate the principles. The pace gain comes from doing the governance work once, at the platform level, not per project." },

  { slug:"human-vs-ai", n:4, title:"Human vs AI",
    teaser:"When to use which, and how to design the handoff so context flows.",
    tension:"For every interaction, the brand has to decide: human, AI, or some combination \u2014 and the answer changes by use case, customer, channel, and moment. The tension is real on both sides. Push too far toward AI and the brand loses the empathy moments that define the relationship; lean too far on humans and the cost base makes the business unsustainable. Compounding this, the AI/human boundary isn\u2019t stable: capabilities that needed humans last year don\u2019t this year, and customers\u2019 expectations move with the technology. Static design choices age badly.",
    persists:"Most contact centres are organised around the assumption that humans are the default and AI handles the overflow \u2014 but the economics, the customer expectations, and the technology all argue the inverse: AI is the default for resolvable interactions, humans handle the moments that matter. Re-orienting the operating model around that inversion is hard. It touches workforce planning, hiring profiles, training, agent role design, union relationships, and works council narratives. The tension persists because the answer isn\u2019t a feature choice \u2014 it\u2019s an operating-model change.",
    play:"[[autonomy-spectrum|The autonomy spectrum]] is the design vocabulary \u2014 different use cases at different levels intentionally. [[agent-assist|Agent Copilot]] is the resolution of the tension at the interaction level: AI doing the work that lets humans focus on judgement. [[orchestration|Orchestration]] ensures handoffs between AI and human are seamless to the customer. [[first-touch-resolution|First-touch resolution]] is the metric that holds the whole system accountable: did the customer get what they needed, regardless of who delivered it? Together these turn \u201Chuman or AI\u201D from a binary into a designed flow.",
    reconcile:"The pattern in EMEA brands getting this right is to invert the default: AI handles transactional and informational journeys end-to-end; humans handle relational, complex, and high-stakes moments \u2014 and the AI hands off rich context when escalation is needed. Workforce planning shifts from \u201Cagents handle volume\u201D to \u201Cagents handle judgement\u201D, with hiring profiles and training following. Works council and union conversations centre on the upskilling story, not the headcount story. The brands that handle this well treat their agents as the higher-value layer the AI exists to enable, not the cheaper layer the AI exists to replace." },

  { slug:"universal-ai-vs-orchestrated-ai", n:5, title:"Universal AI vs orchestrated AI",
    teaser:"Point-solution AI features vs an AI-coordinated journey.",
    tension:"Every category in the contact centre stack now has an \u201CAI version\u201D \u2014 AI routing, AI knowledge, AI agent assist, AI analytics, AI virtual agents. A brand can buy each from a different best-of-breed vendor and assemble a stack of universal AI capabilities. Alternatively, they can buy an orchestrated AI platform where every capability shares one data model, one governance layer, one journey view. The tension is real: best-of-breed offers depth in each capability; orchestration offers coherence across them. The honest answer is that depth without coherence costs more than it saves.",
    persists:"The contact centre buying pattern is procurement-led, RFP-driven, and feature-graded \u2014 which structurally favours best-of-breed. Buying frameworks reward capability depth (does the routing engine support these 23 features?) over architectural coherence (does the routing engine share context with the agent assist engine?). Vendors, including the orchestration platforms, often respond to RFPs feature-by-feature rather than architecture-first. The tension persists because the buying motion encourages assembling AI features rather than designing an AI architecture.",
    play:"[[orchestration|Orchestration]] is the alternative the tension is named after \u2014 the architectural choice that makes loyalty and efficiency compound rather than trade. [[knowledge-management|Knowledge management]] is where best-of-breed fragmentation shows first (multiple sources of truth). [[routing|Routing]] shows the cost of architectural fragmentation second (predictions decoupled from outcomes). [[agent-assist|Agent Copilot]] shows it at the agent\u2019s screen (AI tab sprawl). [[hallucination-mitigation|Hallucination mitigation]] is where it becomes a regulatory problem (mitigation gaps across vendor boundaries).",
    reconcile:"The reconciliation pattern is to evaluate AI architecturally before evaluating it feature-by-feature: \u201Cwhat data flows where, governed how, audited by whom\u201D before \u201Cwhich vendor\u2019s routing engine has the most ML features\u201D. Brands that lead with this question end up consolidating onto orchestration platforms even when individual features score lower in feature matrices, because the architectural cost of integration shows up later. The shift is from procurement-led RFPs to architecture-led evaluations, with TCO modelled across three years and including the integration burden honestly." }
];
